---
version: '3.2'

services:
  logstash:
    image: "docker.elastic.co/logstash/logstash:6.4.3"
    volumes:
      - containers/logstash/twitter.conf:/usr/share/logstash/pipeline/twitter.conf

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.4.3"
    environment:
      - "discovery.type=single-node"

  kibana:
    image: "docker.elastic.co/kibana/kibana:6.4.3"
    ports:
      - 5601:5601

