---
version: '2.4'

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.4.3"
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    mem_limit: 2G
    memswap_limit: 0
    mem_reservation: 2G
    volumes:
      - "es_data:/usr/share/elasticsearch/data"

  ingress:
    build:
      context: containers/ingress
      dockerfile: Dockerfile
    environment:
      - "ES_HOST=elasticsearch"
      - "CONSUMER_KEY=${CONSUMER_KEY}"
      - "CONSUMER_SECRET=${CONSUMER_SECRET}"
      - "HASHTAGS=${HASHTAGS}"
      - "OAUTH_KEY=${OAUTH_KEY}"
      - "OAUTH_SECRET=${OAUTH_SECRET}"

      - "LOG_LEVEL=${LOG_LEVEL:-INFO}"
    depends_on:
      - elasticsearch
    restart: always

  kibana:
    image: "docker.elastic.co/kibana/kibana:6.4.3"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  es_data:
