---
version: '2.4'

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.4.3"
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    mem_limit: 2G
    memswap_limit: 0
    mem_reservation: 2G

  ingress:
    build:
      context: containers/ingress
      dockerfile: Dockerfile
    environment:
      - "CONSUMER_KEY=${CONSUMER_KEY}"
      - "CONSUMER_SECRET=${CONSUMER_SECRET}"
      - "HASHTAGS=${HASHTAGS}"
      - "OAUTH_KEY=${OAUTH_KEY}"
      - "OAUTH_SECRET=${OAUTH_SECRET}"

      - "LOG_LEVEL=${LOG_LEVEL:-DEBUG}"
    depends_on:
      - elasticsearch

  kibana:
    image: "docker.elastic.co/kibana/kibana:6.4.3"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
